// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CollegefinderTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void collegefinder() {
    driver.get("https://yocket.com/feed");
    driver.manage().window().setSize(new Dimension(1296, 688));
    driver.findElement(By.id("college-finder")).click();
    driver.findElement(By.cssSelector("a:nth-child(2) > .w-full")).click();
    driver.findElement(By.cssSelector("#vs1__combobox .vs__search")).click();
    driver.findElement(By.cssSelector("#vs1__combobox .vs__search")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector("#vs1__combobox .vs__search")).sendKeys("united");
    driver.findElement(By.cssSelector("#vs1__combobox .vs__search")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("vs2__combobox")).click();
    driver.findElement(By.cssSelector("#vs2__combobox .vs__search")).sendKeys("computer s");
    driver.switchTo().frame(0);
    driver.findElement(By.cssSelector(".win_close")).click();
    driver.switchTo().defaultContent();
    driver.findElement(By.cssSelector("#vs2__combobox .vs__search")).click();
    driver.findElement(By.cssSelector("#vs2__combobox .vs__search")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector("#vs2__combobox .vs__search")).sendKeys("computer sc");
    driver.findElement(By.cssSelector("#vs2__combobox .vs__search")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".px-6")).click();
    driver.findElement(By.cssSelector("#vs4__combobox .vs__search")).click();
    driver.findElement(By.cssSelector("#vs4__combobox .vs__search")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector("#vs4__combobox .vs__search")).sendKeys("aurora");
    driver.findElement(By.cssSelector("#vs4__combobox .vs__search")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("#vs6__combobox > .vs__selected-options")).click();
    driver.findElement(By.cssSelector("#vs6__combobox > .vs__selected-options")).click();
    driver.findElement(By.cssSelector("#vs6__combobox > .vs__selected-options")).click();
    driver.findElement(By.cssSelector("#vs6__combobox .vs__search")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector("#vs6__combobox .vs__search")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector("#vs6__combobox .vs__search")).sendKeys(Keys.DOWN);
    driver.findElement(By.cssSelector("#vs6__combobox .vs__search")).sendKeys("computer");
    driver.findElement(By.cssSelector("#vs6__combobox .vs__search")).sendKeys(Keys.ENTER);
    driver.findElement(By.id("marks")).click();
    driver.findElement(By.id("marks")).sendKeys("8");
    driver.findElement(By.cssSelector(".px-6")).click();
    driver.findElement(By.cssSelector(".grid:nth-child(2) > div:nth-child(1) > .bg-white > .text-sm")).click();
    driver.findElement(By.id("toefl_overall_score")).click();
    driver.findElement(By.id("toefl_overall_score")).sendKeys("120");
    driver.findElement(By.cssSelector(".md\\3Agrid-cols-3 > div:nth-child(3) > .bg-white")).click();
    driver.findElement(By.cssSelector(".px-6")).click();
    driver.findElement(By.cssSelector(".px-6")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".px-6"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".bg-transparent")).click();
    {
      WebElement dropdown = driver.findElement(By.cssSelector(".bg-transparent"));
      dropdown.findElement(By.xpath("//option[. = 'Cost']")).click();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".hover\\3Atext-orange-500:nth-child(2)"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.close();
  }
}
